### ISSUE TITLE
Deploy to Maximo - Screens - ClassNotFoundException

### ISSUE THREAD

**Issue by jaredschrag** [sharptree/vscode-autoscript-deploy#15]
I'm on Maximo 7.6.1.3 (IFIX018) and using v1.13.5 of the Sharptree VSCode extension and am noticing that any reference to a class in the `psdi.webclient.system.controller` package (via `Java.type(...)`) will encounter the `java.lang.ClassNotFoundException`. How are these java classes not in the classpath and available to Automation Scripting?

**Comment by jaredschrag** [comment]
I tested two Automation Scripts within Maximo, one using `jython`, one using `nashorn`, and I found that both scripts, when tested from the Automation Scripting application within the Maximo front-end, successfully instance the `psdi.webclient.system.controller.PresentationLoader` Class (or any other fully qualified Class within the set of `psdi.webclient` packages). However, when the VSCode extension causes the `SHARPTREE.AUTOSCRIPT.SCREENS` Automation Script to execute, it seems that any Class in any `psdi.webclient` package will encounter the `java.lang.ClassNotFoundException`. Not sure what to make of that.

This Maximo environment is using SSL, and uses LDAP/SSO authentication for the application. I've configured the VSCode extension with an Maximo API key and I've seen it successfully extract Screen presentation - just fails to deploy. Sometimes, right after extracting a screen successfully, I attempt to deploy the extracted screen presentation, and it gets a different error:
![Sharptree_Error_DeployScreen](https://github.com/sharptree/vscode-autoscript-deploy/assets/143452984/72006d4a-8574-4864-ae99-27a6ada22896)
Here is the Server SystemErr.log when this happens:
```
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R java.lang.Exception
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at psdi.util.logging.Log4jLogger.error(Log4jLogger.java:379)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at psdi.util.logging.Log4jLogger.error(Log4jLogger.java:347)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_V(VirtualHandle.java:85)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.FilterArgumentsHandle.invokeExact_thunkArchetype_X(FilterArgumentsHandle.java:85)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.FilterReturnHandle.invokeExact_thunkArchetype_X(FilterReturnHandle.java:59)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:398)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:69)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at jdk.nashorn.internal.scripts.Script$Recompilation$37$2244$\^eval\_.main(<eval>:165)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:69)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at jdk.nashorn.internal.scripts.Script$23$\^eval\_.:program(<eval>:51)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:649)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:506)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:405)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:433)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:85)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:526)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.tivoli.maximo.script.JSR223ScriptDriver.evalScript(JSR223ScriptDriver.java:287)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.tivoli.maximo.script.AbstractScriptDriver.runScript(AbstractScriptDriver.java:155)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.tivoli.maximo.oslc.provider.ScriptRouteHandler.handleScriptCall(ScriptRouteHandler.java:104)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.tivoli.maximo.oslc.provider.ScriptRouteHandler.handleRequest(ScriptRouteHandler.java:62)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.tivoli.maximo.oslc.provider.MaximoOslcProviderServlet.handleRoute(MaximoOslcProviderServlet.java:1300)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.tivoli.maximo.oslc.provider.MaximoOslcProviderServlet.processPostPut(MaximoOslcProviderServlet.java:1412)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.tivoli.maximo.oslc.provider.MaximoOslcProviderServlet.doPost(MaximoOslcProviderServlet.java:266)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:143)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:96)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.tivoli.maximo.filter.UnSupportedMethodBlockFilter.doFilter(UnSupportedMethodBlockFilter.java:60)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at psdi.webclient.system.filter.HttpXFrameOptionsFilter.doFilter(HttpXFrameOptionsFilter.java:38)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at psdi.webclient.system.filter.MTContextFilter.doFilter(MTContextFilter.java:53)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:979)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1119)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:966)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:289)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.ssl.channel.impl.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1188)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.ssl.channel.impl.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:695)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
[4/19/24 9:36:07:632 CDT] 00000265 SystemErr     R 	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)

```

**Comment by jvenhuizen** [comment]
There is an issue where sometimes Maximo has the UI components available and sometimes not when executing the automation script, so this has been hit or miss to reproduce.  We have gone a head and created a fallback mechanism that just updates the presentation.xml directly, but this unfortunately will not trigger a UI refresh, which may not actually be a big deal.
